<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>de.payne</groupId>
  <artifactId>kinggungame</artifactId>
<!-- VERSION AUCH IN PLUGIN.YML  -->
  <version>1.0.0</version>
  <packaging>jar</packaging>
<!-- PLUGIN INFORMATION AUCH IN PLUGIN.YML --> 
  <name>KingGunGame</name>
  <description>Kings GunGame Plugin</description>
  <url>htps://www.king-gaming.eu</url>
  
<!-- CREDITS  -->
  <developers>
  	<developer>
  		<name>Felix Payne</name>
  	</developer>
  </developers>
  
<!--  AUTHOR AND MAINCLASS USED IN PLUGIN.YML -->
  <properties>
  	<author>Felix Payne</author>
    <mainClass>de.payne.gungame.GunGame</mainClass>
	<!-- Removes warnings -->
  </properties>
  
<!-- REPOSITORIES  -->
  <repositories>
    <!-- FOR SPIGOT  -->
   	<repository>
  		<id>spigot-repo</id>
  		<url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
  	</repository>
    <!-- FOR HOLOGRAPHIC DISPLAYS  -->
	<repository>
   	 <id>codemc-repo</id>
   	 <url>https://repo.codemc.io/repository/maven-public/</url>
	</repository>
    <!-- FOR PAPERMC  -->
  	<repository>
    <id>papermc</id>
    <url>https://papermc.io/repo/repository/maven-public/</url>
</repository>
  	<!-- FOR GITHUB PROJECTS  -->
  	<repository>
  	  	<id>jitpack.io</id>
        <url>https://jitpack.io</url>
  	</repository>
    <repository>
        <id>minecraft-repo</id>
        <url>https://libraries.minecraft.net/</url>
    </repository>
  </repositories>
  <!-- DEPENDENCIES  -->
  <dependencies>
  <!-- FOR PAPER  -->
	<dependency>
  		 <groupId>com.destroystokyo.paper</groupId>
   		 <artifactId>paper-api</artifactId>
   		 <version>1.16.5-R0.1-SNAPSHOT</version>
   		 <scope>provided</scope>
	</dependency>
    <!-- FOR SPIGOT  -->
<!--   	<dependency>
  		 <groupId>org.spigotmc</groupId>
         <artifactId>spigot-api</artifactId>
         <version>1.16.5-R0.1-SNAPSHOT</version>
         <scope>provided</scope>
  	</dependency> -->
    <!-- FOR HOLOGRAPHIC DISPLAYS  -->
	<dependency>
    	<groupId>com.gmail.filoghost.holographicdisplays</groupId>
    	<artifactId>holographicdisplays-api</artifactId>
    	<version>2.4.0</version>
    	<scope>provided</scope>
	</dependency>
  	<!-- FOR MYSQL -->
	<dependency>
    	<groupId>mysql</groupId>
    	<artifactId>mysql-connector-java</artifactId>
  	 	 <version>8.0.23</version>
	</dependency>
	<!-- FOR AUTHLIB  -->
      <dependency> 
        <groupId>com.mojang</groupId>
        <artifactId>authlib</artifactId>
        <version>1.5.25</version>
        <scope>provided</scope>
    </dependency> 
	<!-- FOR LOMBOK  -->
	<dependency>
		<groupId>org.projectlombok</groupId>
		<artifactId>lombok</artifactId>
		<version>1.18.16</version>
		<scope>provided</scope>
	</dependency>
		<!-- FOR SPIGOT_SERVER DATA  -->
<!-- 	<dependency>
    <groupId>org.spigotmc</groupId>
    <artifactId>spigot</artifactId>
    <version>1.16.5-R0.1-SNAPSHOT</version>
	</dependency> -->
  </dependencies>
  
<build>
    <sourceDirectory>src/main/java</sourceDirectory>
    <defaultGoal>clean install</defaultGoal>
    
    <resources>
      <resource>
        <directory>${basedir}/src/main/resources</directory>
        <filtering>true</filtering>
        	<includes>
        		<include>plugin.yml</include>
        		<include>config.yml</include>
        		<include>level.yml</include>
        		<include>messages.yml</include>
        	</includes>
      </resource>
      <resource>
      	<directory>src/main/resources</directory>
      	<filtering>false</filtering>
      	<excludes>
          <exclude>**/*.java</exclude>
          <exclude>*.yml</exclude>
        </excludes>
      </resource>
    </resources>
    
    <!-- COMPILE  -->
	<plugins>
		<!-- Sets the Java version to 8 -->
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.8.1</version>
			<configuration>
				<source>1.8</source>
				<target>1.8</target>
			</configuration>
		</plugin>
		<!-- Sets the custom JARfile name (Project name without spaces is good) -->
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-jar-plugin</artifactId>
			<version>3.2.0</version>
			<configuration>
				<finalName>${project.name}</finalName>
			</configuration>
		</plugin>
	</plugins>
  </build>
</project>